# Generated by Django 4.2.5 on 2023-09-26 14:46

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('task_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('task_title', models.CharField(max_length=200)),
                ('task_description', models.TextField()),
                ('task_categorie', models.CharField(max_length=100)),
                ('task_status', models.CharField(max_length=50)),
            ],
        ),
    ]
